import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import {
  assertGeneratedArtifact,
  assertNetworkCatalogIdentity,
  assertProvenanceManifestIdentity,
} from "../../app/data/artifacts/decoders";
import { generateAll } from "../../scripts/wt6/generate";

const GENERATED_DIRECTORY = path.resolve("app/data/generated");
const EXPECTED_ARTIFACTS = [
  ["approved-inputs-manifest-v1", "approved-inputs-manifest-v1.json"],
  ["forecast-snapshot-v3", "forecast-snapshot-v3.json"],
  ["snapshot-evaluation-v3", "snapshot-evaluation-v3.json"],
  ["market-reference-v1", "market-reference-v1.json"],
  ["port-traffic-fixture-v1", "port-traffic-fixture-v1.json"],
  ["chokepoint-traffic-fixture-v1", "chokepoint-traffic-fixture-v1.json"],
  ["news-policy-v18", "news-policy-v18.json"],
  ["insight-policy-v1", "insight-policy-v1.json"],
  ["tuning-config-v1", "tuning-config-v1.json"],
  ["network-catalog-seam-v1", "network-catalog-seam-v1.json"],
  ["network-catalog-seam-identity-v1", "network-catalog-seam-identity-v1.json"],
  ["fixture-catalog-v1", "fixture-catalog-v1.json"],
  ["provenance-manifest-v1", "provenance-manifest-v1.json"],
  ["provenance-manifest-identity-v1", "provenance-manifest-identity-v1.json"],
] as const;

function digest(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

async function artifact(fileName: string): Promise<{
  readonly bytes: Buffer;
  readonly value: unknown;
}> {
  const bytes = await readFile(path.join(GENERATED_DIRECTORY, fileName));
  assert.equal(bytes[0], 0x7b, `${fileName} must start with an object byte`);
  assert.equal(bytes.at(-1), 0x0a, `${fileName} must end with one LF`);
  assert.notEqual(bytes.at(-2), 0x0a, `${fileName} must have one trailing LF`);
  return { bytes, value: JSON.parse(bytes.toString("utf8")) };
}

test("all producer artifacts pass their method-specific runtime decoder", async () => {
  for (const [logicalId, fileName] of EXPECTED_ARTIFACTS) {
    const { value } = await artifact(fileName);
    assertGeneratedArtifact(logicalId, value);
  }
});

test("provenance records every derived artifact with matching canonical identity", async () => {
  const { bytes: provenanceBytes, value: provenanceValue } = await artifact(
    "provenance-manifest-v1.json",
  );
  const { value: provenanceIdentity } = await artifact(
    "provenance-manifest-identity-v1.json",
  );
  await assertProvenanceManifestIdentity(provenanceBytes, provenanceIdentity);

  const provenance = provenanceValue as {
    readonly referenceManifestSha256: string;
    readonly artifacts: readonly {
      readonly logicalArtifactId: string;
      readonly byteSize: number;
      readonly sha256: string;
      readonly validation: string;
    }[];
  };
  assert.equal(
    provenance.referenceManifestSha256,
    "47f01f91233e63a59207daf154246113a84abb1587bea168f618a83d21798e93",
  );
  const filesById = new Map(EXPECTED_ARTIFACTS);
  for (const entry of provenance.artifacts) {
    const fileName = filesById.get(entry.logicalArtifactId as (typeof EXPECTED_ARTIFACTS)[number][0]);
    assert.ok(fileName, `unknown provenance artifact ${entry.logicalArtifactId}`);
    const bytes = await readFile(path.join(GENERATED_DIRECTORY, fileName));
    assert.equal(entry.byteSize, bytes.length);
    assert.equal(entry.sha256, digest(bytes));
    assert.equal(entry.validation, "PASS");
  }
});

test("network catalog identity is bound to generated bytes and approved counts", async () => {
  const catalog = await artifact("network-catalog-seam-v1.json");
  const identity = await artifact("network-catalog-seam-identity-v1.json");
  await assertNetworkCatalogIdentity(catalog.bytes, catalog.value, identity.value);
  const typed = identity.value as {
    readonly routeCount: number;
    readonly portCount: number;
    readonly uniquePortSeriesCount: number;
    readonly chokepointCount: number;
    readonly weatherCount: number;
  };
  assert.deepEqual(
    [
      typed.routeCount,
      typed.portCount,
      typed.uniquePortSeriesCount,
      typed.chokepointCount,
      typed.weatherCount,
    ],
    [13, 57, 56, 11, 82],
  );
});

test("snapshot cardinality, ordering, and KNEI SARIMAX golden values are retained", async () => {
  const { value } = await artifact("forecast-snapshot-v3.json");
  const snapshot = value as {
    readonly dates: readonly string[];
    readonly routes: Readonly<
      Record<
        string,
        {
          readonly values: readonly number[];
          readonly models: readonly {
            readonly id: string;
            readonly forecasts: readonly {
              readonly horizon: number;
              readonly value: number;
              readonly lower90: number;
              readonly upper90: number;
            }[];
            readonly metricsByHorizon: readonly {
              readonly horizon: number;
              readonly mapePct: number;
              readonly mase: number;
              readonly coverage90Pct: number;
            }[];
          }[];
        }
      >
    >;
  };
  assert.equal(snapshot.dates.length, 187);
  assert.equal(Object.keys(snapshot.routes).length, 13);
  assert.ok(Object.values(snapshot.routes).every((route) => route.values.length === 187));
  assert.ok(Object.values(snapshot.routes).every((route) => route.models.length === 8));
  assert.ok(
    Object.values(snapshot.routes).every((route) =>
      route.models.every((model) =>
        model.forecasts.map((forecast) => forecast.horizon).join(",") === "1,2,3,4",
      ),
    ),
  );

  const knei = snapshot.routes.KNEI;
  assert.equal(snapshot.dates.at(-1), "2026-08-03");
  assert.equal(knei.values.at(-1), 4_884);
  const sarimax = knei.models.find((model) => model.id === "sarimax");
  assert.ok(sarimax);
  assert.deepEqual(sarimax.forecasts[0], {
    horizon: 1,
    date: "2026-08-10",
    value: 4_828.98,
    lower90: 4_482.47,
    upper90: 5_175.49,
    calibrationSampleSize: 78,
  });
  assert.equal(sarimax.metricsByHorizon[0].mapePct, 3.6);
  assert.equal(sarimax.metricsByHorizon[0].mase, 0.037);
  assert.equal(sarimax.metricsByHorizon[0].coverage90Pct, 88.5);
});

test("fixture truth preserves reference, stale, unavailable, null, and observed zero", async () => {
  const { value: fixtureValue } = await artifact("fixture-catalog-v1.json");
  const fixture = fixtureValue as {
    readonly items: readonly {
      readonly domain: string;
      readonly state: string;
      readonly mode: string;
      readonly asOf: string | null;
      readonly artifactDigest: string | null;
      readonly expectedCacheControl: string;
    }[];
  };
  assert.ok(fixture.items.some((item) => item.domain === "market" && item.state === "REFERENCE" && item.mode === "reference"));
  assert.ok(fixture.items.some((item) => item.domain === "port" && item.state === "STALE" && item.mode === "fixture" && item.asOf === "2026-08-07"));
  assert.ok(fixture.items.some((item) => item.domain === "chokepoint" && item.state === "STALE" && item.asOf === "2026-08-09"));
  assert.ok(
    fixture.items
      .filter((item) => item.state === "UNAVAILABLE")
      .every(
        (item) =>
          item.mode === "unavailable" &&
          item.asOf === null &&
          item.artifactDigest === null &&
          item.expectedCacheControl === "no-store",
      ),
  );

  const { value: portValue } = await artifact("port-traffic-fixture-v1.json");
  const port = portValue as {
    readonly summaries: Readonly<
      Record<
        string,
        {
          readonly previousEstimatedTotalTons7d: number | null;
          readonly estimatedTotalTonsChangePercent: number | null;
          readonly previousContainerVesselCalls7d: number | null;
          readonly vesselCallsChangePercent: number | null;
        }
      >
    >;
    readonly details: Readonly<
      Record<
        string,
        {
          readonly points: readonly {
            readonly estimatedTotalTons: number | null;
            readonly containerVesselCalls: number | null;
          }[];
        }
      >
    >;
  };
  assert.ok(
    Object.values(port.summaries).some(
      (summary) =>
        (summary.previousEstimatedTotalTons7d === 0 && summary.estimatedTotalTonsChangePercent === null) ||
        (summary.previousContainerVesselCalls7d === 0 && summary.vesselCallsChangePercent === null),
    ),
  );
  assert.ok(
    Object.values(port.details).some((detail) =>
      detail.points.some(
        (point) => point.estimatedTotalTons === 0 || point.containerVesselCalls === 0,
      ),
    ),
  );
});

test("decoders reject extra keys, malformed domain data, and mismatched identities", async () => {
  const snapshot = structuredClone(
    (await artifact("forecast-snapshot-v3.json")).value,
  ) as Record<string, unknown>;
  snapshot.extra = true;
  assert.throws(() => assertGeneratedArtifact("forecast-snapshot-v3", snapshot), /keys/u);

  const market = structuredClone(
    (await artifact("market-reference-v1.json")).value,
  ) as {
    series: { harpex: { unit: string } };
  };
  market.series.harpex.unit = "index points";
  assert.throws(() => assertGeneratedArtifact("market-reference-v1", market), /Index/u);

  const port = structuredClone(
    (await artifact("port-traffic-fixture-v1.json")).value,
  ) as {
    summaries: Record<string, { portId: string }>;
  };
  const firstPortKey = Object.keys(port.summaries)[0];
  port.summaries[firstPortKey].portId = "wrong-id";
  assert.throws(() => assertGeneratedArtifact("port-traffic-fixture-v1", port), /portId/u);

  const catalog = await artifact("network-catalog-seam-v1.json");
  const identity = structuredClone(
    (await artifact("network-catalog-seam-identity-v1.json")).value,
  ) as { catalogSeamSha256: string };
  identity.catalogSeamSha256 = "0".repeat(64);
  await assert.rejects(
    assertNetworkCatalogIdentity(catalog.bytes, catalog.value, identity),
    /identity/u,
  );
});

test("generated artifacts contain no local or quarantined implementation lineage", async () => {
  const forbidden = /(?:cargo-rescue-network|ZOO_WORKTREES|MOVE_AI_WORKTREES|[A-Z]:\\|19_KCCI_ROUTE_TRENDS_REFERENCE\.html)/u;
  for (const [, fileName] of EXPECTED_ARTIFACTS) {
    const text = (await artifact(fileName)).bytes.toString("utf8");
    assert.doesNotMatch(text, forbidden, fileName);
  }
});

test(
  "approved XLSX inputs regenerate byte-identical artifacts",
  { skip: !process.env.MOVE_AI_DATA_PACK_ROOT },
  async () => {
    const inputRoot = process.env.MOVE_AI_DATA_PACK_ROOT;
    assert.ok(inputRoot);
    const first = await generateAll({ inputRoot });
    const second = await generateAll({ inputRoot });
    assert.deepEqual(
      first.artifacts.map(({ logicalArtifactId, byteSize, sha256 }) => ({
        logicalArtifactId,
        byteSize,
        sha256,
      })),
      second.artifacts.map(({ logicalArtifactId, byteSize, sha256 }) => ({
        logicalArtifactId,
        byteSize,
        sha256,
      })),
    );
    for (const generated of first.artifacts) {
      const committed = await readFile(
        path.join(GENERATED_DIRECTORY, generated.fileName),
      );
      assert.equal(generated.byteSize, committed.length);
      assert.equal(generated.sha256, digest(committed));
      assert.equal(generated.bytes, committed.toString("utf8"));
    }
  },
);
